#!/bin/sh

printf "making ChangeLog..." 1>&2
rcs2log -i 2 -r . |
sed \
    -e 's,/[^ ]*cvs[^ ]*dictem/,,g' \
    -e 's,cheusov@[^>]*,vle@gmx.net,g' \
    -e 's,author@[^>]*,vle@gmx.net,g' \
    -e 's,author ,Aleksey Cheusov,' \
    -e 's,\(.*\)<\([^@<>]\+\)@\([^@<>]\+\)>\(.*\),\1<\2 at \3}\4,g' \
    > ChangeLog || return 1
printf "done\n" 1>&2
