#!/bin/sh

VERSION=`awk '/defconst.*dictem-version/ {gsub(/"/, ""); print $NF}' dictem.el`

CVSROOT=`cat CVS/Root`
export CVSROOT
VERSION_CVS=`echo ${VERSION} | tr . -`
./make_changelog || exit 1
cp ChangeLog /tmp/dictem.ChangeLog.${VERSION} &&
echo "***** Exporting files for dictem-${VERSION}..." &&
cd /tmp &&
rm -rf /tmp/dictem-${VERSION} /tmp/dictem-${VERSION}.tar* &&
cvs export -d dictem-${VERSION} -r dictem-${VERSION_CVS} dictem &&
cd dictem-${VERSION} &&
mv /tmp/dictem.ChangeLog.${VERSION} ChangeLog &&
chmod -R a+rX,g-w . &&
cd .. &&
echo "***** Taring and gzipping dictem-${VERSION}.tar.gz..." &&
tar cvvf dictem-${VERSION}.tar dictem-${VERSION} &&
gzip -9 dictem-${VERSION}.tar &&
echo "***** Done making /tmp/dictem-${VERSION}.tar.gz"
ls -la dictem-${VERSION}.tar.gz
